### ISSUE TITLE
Android version of the helloiot shows nothing

### ISSUE THREAD

**Issue by CelsoCaldeira** [adrianromero/helloiot#1]
Sorry I downloaded the apk and after installing it shows nothing, only a black screen, no buttons for add item to mount a dashboard.
Do I need to prepare the dashboard first and create the apk after on android studio?

**Comment by adrianromero** [comment]
Hello Celso. The aplication when starting is supposed to show the connection panel, so this is not the right behaviour. What version are you using and what device?

**Comment by adrianromero** [comment]
Testing in a Samsung Galaxy Tab A it takes 8 seconds to display the connection panel, maybe it is just a matter of waiting few seconds.

**Comment by adrianromero** [comment]
Fixed by changeset https://github.com/adrianromero/helloiot/commit/4a241bf18d59e7009dc61ddff3267851d06a9721
