### ISSUE TITLE
Problem when executing on Linux (Raspberry Pi 3)

### ISSUE THREAD

**Issue by sbdraus** [adrianromero/helloiot#2]
I am trying to run application on my RPI3 under Rasbian but all i get is:
"Error: Could not find or load main class com.adr.helloiot.Main.AppClient"

As far as I understand there is no case for "Linux" uname. I used prebuild app (downloaded zip file)

**Comment by adrianromero** [comment]
First be sure to have JavaFX installed properly in the Raspberry Pi. You can follow these instructions: http://docs.gluonhq.com/javafxports/ . If it is still not working, please, specify all the steps you do until you get this error.

**Comment by sbdraus** [comment]
This is truly lack of JavaFx. My bad
Raspberry PI can't be launched just after Rasbian intalation.

In order to get it working on freshly installed Rasbian Stretch Full (I did **not** install any other java):
- install Xorg, then reboot
- install openjfx (from sudo apt-get install), then reboot
- set GL driver to Legacy, then reboot
- run application without any sudo - should work just fine (It is not fully happy but it is working as desired)
