### ISSUE TITLE
Parse JSON

### ISSUE THREAD

**Issue by BIAs91** [adrianromero/helloiot#4]
Good day!
How to parse JSON format to read values without quotes?
Now parse messages on the JSON path $.value
{"value":"300"}
How to parse messages by type?
{"value":300}
Thanks

**Comment by frett27** [comment]
you can apply this patch, it fix it :+1: 
`
diff --git a/src/main/java/com/adr/helloiotlib/format/StringFormatPath.java b/src/main/java/com/adr/helloiotlib/format/StringFormatPath.java
index fb758bb..f9618f8 100644
--- a/src/main/java/com/adr/helloiotlib/format/StringFormatPath.java
+++ b/src/main/java/com/adr/helloiotlib/format/StringFormatPath.java
@@ -58,7 +58,7 @@ public abstract class StringFormatPath extends StringFormat {
         } else {
             // if value null or empty this will throw an exception
             // Note that this is a different behavior when path is null because here we expect a valid JSON.
-            String v = JsonPath.<String>read(new String(value, StandardCharsets.UTF_8), path);
+            String v = "" + JsonPath.<Object>read(new String(value, StandardCharsets.UTF_8), path);
             if (v == null || v.isEmpty()) {
                 return valueImpl(null);
             }



`

**Comment by adrianromero** [comment]
Sorry, this project is no longer updated
