### ISSUE TITLE
Not working on android 10 : getting a black screen

### ISSUE THREAD

**Issue by ouinouin** [adrianromero/helloiot#6]
HI, i d like to evaluate your app unfortunately i get black screen on a galaxy S9 with android 10...
is there a resolution isue or something like that ? is it easy to try to release again your app while compiling with the latest android framework?

**Comment by chinswain** [comment]
Same issue on Android 12, a message is displayed saying it's designed for older phones and then just a black screen.

**Comment by adrianromero** [comment]
Sorry, this project is not longer updated.
